ServerEvents.recipes(event => {
  //event.replaceInput({ input: '' },'','')
  //event.remove({output: '',not:{mod:'kubejs'}})
  //event.remove({"item": ''})
  //event.remove({input: ''})
  //event.custom().id("dut_create:")
  //event.remove({ mod: '' })

  event.remove({ id: "create_things_and_misc:powder_obsi_c_raft" })
  event.remove({ id: "create_things_and_misc:glue_fluid_craft" })
  event.remove({ id: "create_things_and_misc:gluepackagingcraft" })
  event.remove({ id: "create_things_and_misc:mendingrunecraft" })
  event.remove({ id: "create_things_and_misc:vibration_mecanism_craft" })
  event.remove({ id: "create_things_and_misc:slime_boost_craft" })
  event.remove({ id: "create_things_and_misc:brass_knife_craft" })
  event.remove({ id: "create_things_and_misc:zinc_knif_craft" })
  event.remove({ id: "create_things_and_misc:copper_knife_craft" })
  event.remove({ id: "create_things_and_misc:rose_quartz_sheet_craft"})
  event.remove({ id: "create_things_and_misc:experiencesheetcraft" })
  event.remove({ id: "create_things_and_misc:sprinklerheadcraft" })
  event.remove({ id: "create_things_and_misc:neon_tube_craft" })
  event.replaceInput({id:"create_things_and_misc:sprinkler_craft"},"create_things_and_misc:sprinkler_head","#dut_create:belt")
  event.replaceInput({input:"create_things_and_misc:vibration_mechanism"},"create_things_and_misc:vibration_mechanism","vintageimprovements:vibrating_table")
})