BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("crushing_wheel")
    .pattern("ABA")
    .pattern("BCB")
    .pattern("ABA")
    .center("C", "minecraft:stone")
    .where("B", "create:linear_chassis")
    .where("A", "create:andesite_alloy_block")
    .craftingItem("create:wrench")
    .resultItem("4x create:crushing_wheel")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("brass_drone_item")
    .pattern("ACA", "DED")
    .pattern("BGB", "FFF")
    .pattern("AFA", "DFD")
    .center("G", "create:content_observer")
    .where("F", "minecraft:air")
    .where("E", "create:display_link")
    .where("D", "railways:smokestack_diesel")
    .where("C", "create:stockpile_switch")
    .where("B", "create:brass_funnel")
    .where("A", "create:brass_scaffolding")
    .craftingItem("create:wrench")
    .resultItem("create_sa:brass_drone_item")
    .build())
//机械手
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("deployer_x_z")
    .pattern("A")
    .pattern("B")
    .pattern("C")
    .center("C", "minecraft:iron_block")
    .where("B", "create:mechanical_piston")
    .where("A", "create:piston_extension_pole")
    .craftingItem("create_sa:brass_pickaxe")
    .resultItem("create:deployer")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("deployer_y1")
    .pattern("A", "B", "C")
    .center("C", "minecraft:iron_block")
    .where("B", "create:mechanical_piston")
    .where("A", "create:piston_extension_pole")
    .craftingItem("create_sa:brass_pickaxe")
    .resultItem("create:deployer")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("deployer_y2")
    .pattern("C", "B", "A")
    .center("C", "minecraft:iron_block")
    .where("B", "create:mechanical_piston")
    .where("A", "create:piston_extension_pole")
    .craftingItem("create_sa:brass_pickaxe")
    .resultItem("create:deployer")
    .build())
//矿物钻井
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("drilling_machine")
    .pattern("BEB", "IJI")
    .pattern("CGD", "#A#")
    .pattern("BFB", "IHI")
    .center("A", "create:mechanical_arm")
    .where("B", "create:railway_casing")
    .where("C", "create:rotation_speed_controller")
    .where("D", "create:sequenced_gearshift")
    .where("E", "create:elevator_pulley")
    .where("F", "create:mechanical_pump")
    .where("G", "create:mechanical_drill")
    .where("H", "createdieselgenerators:huge_diesel_engine")
    .where("I", "create:brass_funnel")
    .where("J", "create:item_vault")
    .where("#", "minecraft:air")
    .craftingItem("create:wrench")
    .resultItem("createoreexcavation:drilling_machine")
    .build())
//流体钻井
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("extractor")
    .pattern("BFB", "IJI")
    .pattern("CGD", "#A#")
    .pattern("BIB", "IHI")
    .center("A", "create:mechanical_arm")
    .where("B", "create:railway_casing")
    .where("C", "create:rotation_speed_controller")
    .where("D", "create:sequenced_gearshift")
    .where("F", "create:mechanical_pump")
    .where("G", "create:hose_pulley")
    .where("H", "createdieselgenerators:huge_diesel_engine")
    .where("I", "create:fluid_pipe")
    .where("#", "create:smart_fluid_pipe")
    .where("J", "create:item_drain")
    .craftingItem("create:wrench")
    .resultItem("createoreexcavation:extractor")
    .build())
//一阶火箭
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_1_rocket")
    .pattern("#A#", "#B#", "#D#", "#F#", "#F#", "#E#", "###", "###")
    .pattern("A#A", "BCB", "DCD", "FCF", "FCF", "EGE", "#H#", "#F#")
    .pattern("#A#", "#B#", "#D#", "#F#", "#F#", "#E#", "###", "###")
    .where("A", "create:encased_fan")
    .where("B", "createaddition:electric_motor")
    .where("C", "design_decor:industrial_iron_boiler")
    .where("D", "createaddition:alternator")
    .where("E", "design_decor:diagonal_girder")
    .where("F", "create:metal_girder")
    .where("G", "create:industrial_iron_block")
    .center("H", "vintageimprovements:vacuum_chamber")
    .where("#", "minecraft:air")
    .craftingItem("create:wrench")
    .resultItem("ad_astra:tier_1_rocket")
    .build())
//大型锅炉
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("industrial_iron_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .where("A", "create:industrial_iron_block")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:industrial_iron_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("zinc_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .whereTag("A", "forge:storage_blocks/new_zinc")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:zinc_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("brass_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .whereTag("A", "forge:storage_blocks/brass")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:brass_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("gold_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .whereTag("A", "forge:storage_blocks/gold")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:gold_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("copper_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .whereTag("A", "forge:storage_blocks/copper")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:copper_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("cast_iron_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .where("A", "createbigcannons:cast_iron_block")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:cast_iron_boiler_large")
    .build())
BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("andesite_boiler_large")
    .pattern("AAA")
    .pattern("ACA")
    .pattern("AAA")
    .where("A", "create:andesite_alloy_block")
    .center("C", "create:fluid_tank")
    .craftingItem("create:wrench")
    .resultItem("design_decor:andesite_boiler_large")
    .build())