StartupEvents.modifyCreativeTab("kubejs:tab", event => {
	event.displayName = Text.translatable("kubejs.modpack_name")
	event.remove("kubejs:matrix_2")
});
StartupEvents.registry("creative_mode_tab", tab => {
	//基础材料
	tab.create("cbc:aaa_materials")
		.icon(() => Item.of("kubejs:aluminum_slag"))
		.content(() => [
			"kubejs:unknown_prototype",
			"kubejs:carbon_electrode",
			'kubejs:salt',
			//'kubejs:kelp_dust',
			'kubejs:sulphur',
			'kubejs:brine_gel',
			'kubejs:lava_gel',
			'kubejs:mossy_mud',
			'kubejs:slime_crystal',
			"kubejs:red_mushroom_cap_piece",
			"kubejs:brown_mushroom_cap_piece",
			"kubejs:stem_silk",
			"kubejs:strophar_cap_piece",
			"kubejs:aeronos_cap_piece",
			"kubejs:strophar_stem_piece",
			"kubejs:aeronos_stem_piece",
			'kubejs:crushed_coal',
			'kubejs:incomplete_bearing',
			'kubejs:rubber',
			'kubejs:graphite',
			'kubejs:graphene_coil',
			'kubejs:carborundum',
			'kubejs:fiber_fabric',
			'kubejs:lapis_plate',
			'kubejs:silicon_plate',
			'createloveandwar:block_of_polymer',
			'createloveandwar:block_of_duraplas',
			'kubejs:polymer_ingot',
			'kubejs:duraplas_ingot',
			'kubejs:polymer_sheet',
			'kubejs:duraplas_sheet',
			'kubejs:new_zinc_ore',
			'kubejs:new_asurine',
			'kubejs:raw_tin',
			'minecraft:copper_block',
			'minecraft:gold_block',
			'minecraft:iron_block',
			'kubejs:tin_block',
			'kubejs:new_zinc_block',
			'create:crushed_raw_copper',
			'create:crushed_raw_gold',
			'create:crushed_raw_iron',
			'create:crushed_raw_tin',
			'kubejs:new_crushed_raw_zinc',
			'minecraft:copper_ingot',
			'minecraft:gold_ingot',
			'minecraft:iron_ingot',
			'kubejs:new_zinc_ingot',
			'kubejs:tin_ingot',
			'create:copper_sheet',
			'create:golden_sheet',
			'create:iron_sheet',
			'kubejs:tin_sheet',
			'kubejs:new_zinc_sheet',
			'minecraft:gold_nugget',
			'create:copper_nugget',
			'minecraft:iron_nugget',
			'kubejs:tin_nugget',
			'kubejs:new_zinc_nugget',
			"create:andesite_alloy_block",
			"create:industrial_iron_block",
			"create:brass_block",
			'ad_astra:steel_block',
			'ad_astra:desh_block',
			"create:andesite_alloy",
			'kubejs:diorite_alloy',
			'kubejs:granite_alloy',
			'kubejs:industrial_iron_ingot',
			"create:brass_ingot",
			'ad_astra:steel_ingot',
			'ad_astra:desh_ingot',
			'kubejs:industrial_iron_sheet',
			"create:brass_sheet",
			'ad_astra:steel_sheet',
			'ad_astra:desh_sheet',
			'kubejs:industrial_iron_nugget',
			"create:brass_nugget",
			'ad_astra:steel_nugget',
			'ad_astra:desh_nugget',
			'ad_astra:raw_desh',
			'kubejs:aluminum_block',
			'kubejs:aluminum_ingot',
			'kubejs:aluminum_sheet',
			'kubejs:aluminum_slag',
			'kubejs:aluminite_powder',
			'kubejs:aluminite',
			'kubejs:light_composite_plate',
			'kubejs:scrap',
			'kubejs:scrap_1',
			'kubejs:scrap_2',
			'kubejs:scrap_3',
			'kubejs:unsteady_electro_hydro',
			'create:shadow_steel',
			'create:refined_radiance',
			'create:chromatic_compound',
			'kubejs:coin_copper',
			'kubejs:coin_iron',
			'kubejs:coin_gold',
			'kubejs:coin_diamond',
			'kubejs:coin_emerald',
			'kubejs:coin_netherite',
		])
		.displayName = Text.translatable("kubejs.creative_tab.materials")
	//零部件
	tab.create("cbc:aaa_parts")
		.icon(() => Item.of("kubejs:mechanical_core"))
		.content(() => [
			'create:shadow_steel_casing',
			'create:refined_radiance_casing',
			'kubejs:io_mechanism',
			'kubejs:fluid_mechanism',
			'kubejs:mechanical_core',
			'kubejs:circuit_board',
			'kubejs:magenta_circuit_board',
			'kubejs:lime_circuit_board',
			'kubejs:bridge_rectifier',
			'kubejs:bearing',
			'kubejs:planetary_gear',
			'kubejs:cardan_joint',
			'kubejs:differential',
			'kubejs:electric_gear',
			'kubejs:slime_tube',
			'kubejs:bronze_triangle',
			'kubejs:iron_hand',
			'kubejs:uncharged_electrolyzer',
			'kubejs:electrolyzer',
			'kubejs:bullet_shells',
			'kubejs:filled_bullets',
			'kubejs:empty_can',
			"kubejs:disposable_battery",
			"kubejs:chargeable_battery",
			'kubejs:carborundum_lens',
			'kubejs:electro_hydro_capacitor',
			'kubejs:radiator',
			'kubejs:optical_device',
			'kubejs:light_composite_plate',
			'kubejs:rocket_gyro',
			'kubejs:rocket_electric_connector',
			'kubejs:rocket_mechanism',
			'kubejs:fuel_tank',
			'kubejs:gas_tank',
			'kubejs:empty_parts_box',
			'kubejs:steel_parts_box',
			'kubejs:desh_parts_box',
			'kubejs:ostrum_parts_box',
			'kubejs:calorite_parts_box',
			'kubejs:brass_parts_box',
			'kubejs:parts_box',
			'kubejs:satellite_mining_module',
			'kubejs:satellite_scanning_module',
			'kubejs:satellite_scanning_module_local',
			'kubejs:brass_hard_disk',
			'kubejs:aluminum_hard_disk',
			'kubejs:tin_hard_disk',
			'kubejs:navigate_data_empty',
		])
		.displayName = Text.translatable("kubejs.creative_tab.parts")
	//食物与工具
	tab.create("cbc:aaa_tool_food")
		.icon(() => Item.of("kubejs:slime_cola_can"))
		.content(() => [
			'kubejs:anti_warden_bomb',
			'beyonddimensions:net_interface',
			'beyonddimensions:net_terminal_item',
			'ad_astra:wrench',
			'kubejs:scanner',
			'kubejs:position_data',
			"kubejs:steel_impact_drill",
			"kubejs:steel_power_sword",
			"kubejs:rocket_sword",
			'geckojs:stepping_caculator',
			"create:clipboard",
			'kubejs:slime_cola_can',
			'kubejs:french_fries',
			'kubejs:large_fries',
			'kubejs:lamb_kebabs',
			'beyonddimensions:net_member_inviter',
			'beyonddimensions:net_manager_inviter',
			'beyonddimensions:net_gifter',
			'beyonddimensions:net_destroyer',
			'beyonddimensions:net_feeder_item',
			Item.of('kubejs:matrix_2', "{ascii:1,display:{Name:'{\"translate\":\"kubejs.matrix.netcreate\",\"italic\":false}'},matrix:[[[-1,7],[2,-124]],[[1,-3],[5,86]],[[-1,4],[2,-127]],[[-1,7],[4,-106]],[[1,-5],[6,71]],[[-1,4],[3,-128]],[[1,10],[5,90]],[[-1,2],[8,-117]],[[1,3],[2,124]],[[-1,5],[3,-116]],[[1,4],[1,114]],[[-1,6],[2,-128]],[[1,7],[3,67]],[[-1,4],[4,-128]],[[1,5],[2,118]],[[-1,3],[5,-112]],[[1,2],[3,127]],[[-1,4],[4,-117]],[[1,3],[1,117]],[[-1,5],[10,-91]]],no_copy:1}"),
			Item.of('kubejs:matrix_2', "{ascii:1,display:{Name:'{\"translate\":\"kubejs.matrix.netexpand\",\"italic\":false}'},matrix:[[[1,3],[-2,95]],[[-1,4],[1,-124]],[[1,-3],[3,103]],[[-1,2],[-2,-93]],[[1,4],[-1,106]],[[-1,-2],[3,-94]],[[-5,2],[1,-16]],[[10,-3],[7,8]],[[-4,5],[4,-34]],[[3,-7],[4,4]],[[2,13],[5,83]],[[-6,4],[5,-23]],[[11,3],[3,10]],[[8,-5],[6,10]],[[9,2],[5,14]],[[10,7],[2,6]],[[11,4],[5,12]],[[12,5],[12,14]],[[13,6],[-1,7]],[[5,3],[3,26]],[[6,5],[5,21]],[[7,8],[5,22]],[[8,9],[7,13]]],no_copy:1}"),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:32,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:8,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_3","color":"aqua","italic":"false"}\'}}').enchant('minecraft:looting', 11).enchant('minecraft:fortune', 9),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:32,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:12,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench","color":"aqua","italic":"false"}\'}}').enchant('minecraft:knockback', 5).enchant('minecraft:fire_aspect', 2).enchant('minecraft:looting', 7).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:36,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:14,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_5","color":"aqua","italic":"false"}\'}}').enchant('minecraft:looting', 7).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:32,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:16,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]},{Amount:0.15d,AttributeName:"generic.movement_speed",Name:"113",Operation:1,Slot:"mainhand",UUID:[I;114,5141,919,810]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_2","color":"aqua","italic":"false"}\'}}').enchant('minecraft:looting', 7).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:32,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:12,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_1","color":"aqua","italic":"false"}\'}}').enchant('minecraft:knockback', 2).enchant('minecraft:fire_aspect', 1).enchant('minecraft:looting', 7).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:48,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_6","color":"aqua","italic":"false"}\'}}').enchant('minecraft:looting', 15).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:48,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:16,AttributeName:"generic.armor",Name:"112",Operation:0,Slot:"mainhand",UUID:[I;1145,1419,198,10]},{Amount:0.35d,AttributeName:"generic.movement_speed",Name:"113",Operation:1,Slot:"mainhand",UUID:[I;114,5141,919,810]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_7","color":"aqua","italic":"false"}\'}}'),
			Item.of('create:wrench', '{AttributeModifiers:[{Amount:32,AttributeName:"generic.attack_damage",Name:"111",Operation:0,Slot:"mainhand",UUID:[I;11451,4,1919,810]},{Amount:0.75d,AttributeName:"generic.movement_speed",Name:"113",Operation:1,Slot:"mainhand",UUID:[I;114,5141,919,810]}],display:{Name:\'{"translate":"item.kubejs.battle_wrench_4","color":"aqua","italic":"false"}\'}}').enchant('minecraft:looting', 7).enchant('minecraft:fortune', 5),
			Item.of('create:wrench', "{display:{Name:'{\"translate\":\"kubejs.item.first_wrench\",\"italic\":false}'}}").enchant('minecraft:sharpness', 12).enchant('minecraft:fire_aspect', 1).enchant('minecraft:looting', 3).enchant('minecraft:knockback', 7)
		])
		.displayName = Text.translatable("kubejs.creative_tab.food_tool")
	//桶装流体
	tab.create("cbc:aaa_bucket")
		.icon(() => Item.of("kubejs:slime_colloid_bucket"))
		.content(() => [
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"create_things_and_misc:diluted_bonemeal"}},display:{Name:\'{"translate":"fluid.create_things_and_misc.diluted_bonemeal","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"vintageimprovements:sulfur_dioxide"}},display:{Name:\'{"translate":"fluid.vintageimprovements.sulfur_dioxide","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"vintageimprovements:sulfur_trioxide"}},display:{Name:\'{"translate":"fluid.vintageimprovements.sulfur_trioxide","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"kubejs:superheated_steam"}},display:{Name:\'{"translate":"fluid.kubejs.superheated_steam","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"kubejs:slime_coin"}},display:{Name:\'{"translate":"fluid.kubejs.slime_coin","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"kubejs:electro_hydro"}},display:{Name:\'{"translate":"fluid.kubejs.electro_hydro","italic":false}\'}}'),
			Item.of('create:creative_fluid_tank', '{BlockEntityTag:{TankContent:{Amount:32000,FluidName:"kubejs:covariant_heat"}},display:{Name:\'{"translate":"fluid.kubejs.covariant_heat","italic":false}\'}}'),
			'kubejs:fused_alumina_bucket',
			'kubejs:aluminum_bucket',
			'kubejs:desh_bucket',
			'kubejs:tin_bucket',
			'kubejs:silver_bucket',
			'kubejs:new_zinc_bucket',
			'kubejs:gold_bucket',
			'kubejs:iron_bucket',
			'kubejs:copper_bucket',
			'kubejs:brass_bucket',
			'kubejs:industrial_iron_bucket',
			'kubejs:incomplete_steel_bucket',
			//'kubejs:incomplete_steel_1_bucket',
			'createbigcannons:molten_steel_bucket',
			'createbigcannons:molten_cast_iron_bucket',
			'createbigcannons:molten_bronze_bucket',
			'kubejs:slime_colloid_bucket',
			'kubejs:cryogen_bucket',
			'kubejs:air_fluid_bucket',
			'kubejs:nether_air_fluid_bucket',
			'kubejs:end_air_fluid_bucket',
			'kubejs:slimeria_air_fluid_bucket',
			'kubejs:nitric_acid_bucket',
			'kubejs:nitrogen_fertilizer_bucket',
			'kubejs:polymer_bucket',
			'kubejs:duraplas_bucket',
			'kubejs:saline_water_bucket',
			'kubejs:caustic_soda_bucket',
			'kubejs:muriatic_acid_bucket',
			'vintageimprovements:sulfuric_acid_bucket',
			'kubejs:lube_oil_bucket',
			'kubejs:drilling_fluid_bucket',
			'kubejs:refined_oil_bucket',
			'kubejs:chromatic_waste_bucket',
			'kubejs:aeronos_spore_bucket',
			'kubejs:strophar_spore_bucket',
			'kubejs:red_mushroom_spore_bucket',
			'kubejs:brown_mushroom_spore_bucket',
			'kubejs:red_spore_bucket',
			'kubejs:green_spore_bucket',
			'kubejs:blue_spore_bucket',
			'kubejs:singular_spore_bucket',
			'kubejs:nitrogen_bucket',
			'kubejs:nitrogen_dioxide_bucket',
			'kubejs:ammonia_bucket',
			'kubejs:chlorine_bucket',
			'kubejs:carbon_dioxide_bucket',
			'kubejs:natural_gas_bucket',
			'kubejs:ethylene_bucket',
			'kubejs:pressurized_steam_bucket',
			'kubejs:cola_puree_bucket',
			'kubejs:slime_cola_bucket',
			'kubejs:oxygen_bucket',
			'kubejs:hydrogen_bucket',
			'minecraft:water_bucket',
			'minecraft:lava_bucket',
			'minecraft:milk_bucket',
			'create:honey_bucket',
			'createdieselgenerators:crude_oil_bucket',
			'createdieselgenerators:diesel_bucket',
			'createdieselgenerators:gasoline_bucket',
			'createaddition:seed_oil_bucket',
			'createdieselgenerators:ethanol_bucket',
			'createdieselgenerators:biodiesel_bucket'
		])
		.displayName = Text.translatable("kubejs.creative_tab.bucket")
	//机器
	tab.create("cbc:aaa_machine")
		.icon(() => Item.of("kubejs:solar_panel"))
		.content(() => [
			'kubejs:creative_motor_blueprint',
			'kubejs:anti_warden_bomb',
			'kubejs:blueprint_builder',
			'kubejs:trading_station',
			'kubejs:culture_bin',
			'kubejs:difference_engine',
			"kubejs:large_difference_engine",
			"kubejs:electron_tube_computer",
			"kubejs:solar_panel",
			"kubejs:space_elevator_controller",
			"kubejs:launch_pad_controller",
			"kubejs:satellite_station",
			'kubejs:airdrop_station',
			'kubejs:redstone_radar',
			"kubejs:condenser",
			"kubejs:hydropress",
			//"kubejs:hydropress_turner",
			"kubejs:blasting_compressor",
			"kubejs:alloy_furnace",
			"kubejs:huge_crusher",
			"kubejs:shaft_furnace",
			"kubejs:infinity_fetching_pool",
			"kubejs:electrolytic_cell",
			'kubejs:electro_hydro_resonant_tower',
			'kubejs:planting_tower',
			'kubejs:cap_reaping_machine',
			'kubejs:stem_reaping_machine',
			"kubejs:carbon_electrode",
			"kubejs:steam_generator",
			"kubejs:covariant_reactor",
			"kubejs:bronze_fuel_rod",
			"kubejs:assembling_machine",
			"kubejs:construction_station",
			"kubejs:emergency_industrial_platform",
			"kubejs:emergency_industrial_platform_block",
			"kubejs:emergency_industrial_platform_lime",
			"kubejs:emergency_industrial_platform_lime_block",
			"kubejs:emergency_industrial_platform_dark",
			"kubejs:emergency_industrial_platform_dark_block",
			"kubejs:emergency_industrial_platform_space",
			"kubejs:battery_slot",
			'kubejs:filling_machine',
			'kubejs:emptying_machine',
			'kubejs:position_data',
			'kubejs:satellite_mining_module',
			'kubejs:satellite_scanning_module',
			'kubejs:satellite_scanning_module_local',
			'kubejs:satellite',
			'kubejs:carrier_rocket',
			'kubejs:space_elevator',
			'kubejs:airdrop',
			'kubejs:productivity_module',
			'kubejs:productivity_module_2',
			'kubejs:productivity_module_3',
			'kubejs:speed_module',
			'kubejs:speed_module_2',
			'kubejs:speed_module_3',
			'kubejs:efficiency_module',
			'kubejs:efficiency_module_2',
			'kubejs:efficiency_module_3',
		])
		.displayName = Text.translatable("kubejs.creative_tab.machine")
	//生物工程
	tab.create("cbc:aaa_bio")
		.icon(() => Item.of("kubejs:mycetozoan"))
		.content(() => [
			"kubejs:covariant_reactor",
			"kubejs:bronze_fuel_rod",
			"kubejs:culture_bin",
			'kubejs:planting_tower',
			'kubejs:cap_reaping_machine',
			'kubejs:stem_reaping_machine',
			"kubejs:red_mushroom_cap_piece",
			"kubejs:brown_mushroom_cap_piece",
			"kubejs:stem_silk",
			"kubejs:strophar_cap_piece",
			"kubejs:aeronos_cap_piece",
			"kubejs:strophar_stem_piece",
			"kubejs:aeronos_stem_piece",
			'kubejs:yeast',
			'kubejs:chromatic_protozoa',
			'kubejs:peat_protozoa',
			'kubejs:metal_protozoa',
			'kubejs:resonant_bacteria',
			'kubejs:useless_bacteria',
			'kubejs:blaze_chlamydia',
			'kubejs:blaze_mycoplasma',
			'kubejs:blaze_wart',
			'kubejs:cheese_moonalgae',
			'kubejs:phantom_fungus',
			'kubejs:mycetozoan',
			'kubejs:myxomycetes_halophila',
			'kubejs:aeronos_spore_bucket',
			'kubejs:strophar_spore_bucket',
			'kubejs:red_mushroom_spore_bucket',
			'kubejs:brown_mushroom_spore_bucket',
			'kubejs:red_spore_bucket',
			'kubejs:green_spore_bucket',
			'kubejs:blue_spore_bucket',
			'kubejs:singular_spore_bucket',
			'kubejs:empty_culture_plate',
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.milk\",\"italic\":false}'},milk:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.super_fuel\",\"italic\":false}'},super_fuel:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.dye\",\"italic\":false}'},dye:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.fuel\",\"italic\":false}'},fuel:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.mud\",\"italic\":false}'},mud:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.wood_chip\",\"italic\":false}'},wood_chip:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{display:{Name:'{\"translate\":\"kubejs.item.culture.exp\",\"italic\":false}'},exp:1b}"),
			Item.of('kubejs:pasteurized_culture_plate', "{biomass:1b,display:{Name:'{\"translate\":\"kubejs.item.culture.biomass\",\"italic\":false}'}}"),
			Item.of('kubejs:matrix_2', '{RGB:[[[0,0],[0,0]]],matrix:[[[0,0],[0,0]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[-1,1],[2,0]]],matrix:[[[-1,1],[2,0]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[1,0],[2,0]]],matrix:[[[1,0],[2,0]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[2,0],[0,1]]],matrix:[[[2,0],[0,1]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[0,1],[2,0]]],matrix:[[[0,1],[2,0]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[1,1],[3,1]]],matrix:[[[1,1],[3,1]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[1,-1],[-1,1]]],matrix:[[[1,-1],[-1,1]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[0,1],[1,1]]],matrix:[[[0,1],[1,1]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[1,2],[5,3]]],matrix:[[[1,2],[5,3]]]}'),
			Item.of('kubejs:matrix_2', '{RGB:[[[1,-2],[-5,3]]],matrix:[[[1,-2],[-5,3]]]}'),
			Item.of('kubejs:matrix_2', "{ascii:1,display:{Name:'{\"translate\":\"kubejs.matrix.netcreate\",\"italic\":false}'},matrix:[[[-1,7],[2,-124]],[[1,-3],[5,86]],[[-1,4],[2,-127]],[[-1,7],[4,-106]],[[1,-5],[6,71]],[[-1,4],[3,-128]],[[1,10],[5,90]],[[-1,2],[8,-117]],[[1,3],[2,124]],[[-1,5],[3,-116]],[[1,4],[1,114]],[[-1,6],[2,-128]],[[1,7],[3,67]],[[-1,4],[4,-128]],[[1,5],[2,118]],[[-1,3],[5,-112]],[[1,2],[3,127]],[[-1,4],[4,-117]],[[1,3],[1,117]],[[-1,5],[10,-91]]],no_copy:1}"),
			Item.of('kubejs:matrix_2', "{ascii:1,display:{Name:'{\"translate\":\"kubejs.matrix.netexpand\",\"italic\":false}'},matrix:[[[1,3],[-2,95]],[[-1,4],[1,-124]],[[1,-3],[3,103]],[[-1,2],[-2,-93]],[[1,4],[-1,106]],[[-1,-2],[3,-94]],[[-5,2],[1,-16]],[[10,-3],[7,8]],[[-4,5],[4,-34]],[[3,-7],[4,4]],[[2,13],[5,83]],[[-6,4],[5,-23]],[[11,3],[3,10]],[[8,-5],[6,10]],[[9,2],[5,14]],[[10,7],[2,6]],[[11,4],[5,12]],[[12,5],[12,14]],[[13,6],[-1,7]],[[5,3],[3,26]],[[6,5],[5,21]],[[7,8],[5,22]],[[8,9],[7,13]]],no_copy:1}")
		])
		.displayName = Text.translatable("kubejs.creative_tab.bio")
	//精算工程
	tab.create("cbc:aaa_caculate")
		.icon(() => Item.of("kubejs:aluminum_hard_disk"))
		.content(() => [
			'geckojs:stepping_caculator',
			"create:clipboard",
			'kubejs:difference_engine',
			"kubejs:electron_tube_computer",
			"kubejs:large_difference_engine",
			'kubejs:blueprint_builder',
			'kubejs:redstone_radar',
			'kubejs:brass_hard_disk',
			'kubejs:aluminum_hard_disk',
			'kubejs:tin_hard_disk',
			'kubejs:navigate_data_empty',
			'kubejs:position_data',
			'kubejs:productivity_module',
			'kubejs:productivity_module_2',
			'kubejs:productivity_module_3',
			'kubejs:speed_module',
			'kubejs:speed_module_2',
			'kubejs:speed_module_3',
			'kubejs:efficiency_module',
			'kubejs:efficiency_module_2',
			'kubejs:efficiency_module_3'
		])
		.displayName = Text.translatable("kubejs.creative_tab.caculate")
	//太空时代
	tab.create("cbc:aaa_space")
		.icon(() => Item.of("kubejs:satellite"))
		.content(() => [
			"kubejs:emergency_industrial_platform_space",
			"kubejs:space_elevator_controller",
			'kubejs:electro_hydro_resonant_tower',
			"kubejs:launch_pad_controller",
			"kubejs:satellite_station",
			'kubejs:airdrop_station',
			'kubejs:redstone_radar',
			"kubejs:solar_panel",
			'kubejs:satellite',
			'kubejs:carrier_rocket',
			'kubejs:space_elevator',
			'kubejs:airdrop',
			'kubejs:optical_device',
			'kubejs:light_composite_plate',
			'kubejs:radiator',
			'kubejs:rocket_gyro',
			'kubejs:rocket_electric_connector',
			'kubejs:rocket_mechanism',
			'kubejs:fuel_tank',
			'kubejs:gas_tank',
			'kubejs:empty_parts_box',
			'kubejs:steel_parts_box',
			'kubejs:desh_parts_box',
			'kubejs:ostrum_parts_box',
			'kubejs:calorite_parts_box',
			'kubejs:brass_parts_box',
			'kubejs:parts_box',
			'kubejs:satellite_mining_module',
			'kubejs:satellite_scanning_module',
			'kubejs:satellite_scanning_module_local',
			'kubejs:scrap',
			'kubejs:scrap_1',
			'kubejs:scrap_2',
			'kubejs:scrap_3',
			'kubejs:unsteady_electro_hydro',
			'kubejs:electro_hydro_capacitor',
			'kubejs:position_data',
			'kubejs:navigate_data_empty',
			'kubejs:navigate_data_earth',
			'kubejs:navigate_data_earth_orbit',
			'kubejs:navigate_data_moon',
			'kubejs:navigate_data_moon_orbit',
			'kubejs:navigate_data_slimeria',
			'kubejs:navigate_data_slimeria_orbit',
			'kubejs:navigate_data_glacio',
			'kubejs:navigate_data_glacio_orbit',
			Item.of('ad_astra:tier_1_rocket', '{BotariumData:{StoredFluids:[{Amount:3000,Fluid:"kubejs:rocket_fuel"}]}}'),
			"ad_astra:launch_pad"
		])
		.displayName = Text.translatable("kubejs.creative_tab.space")
	//未完成零部件
	tab.create("cbc:aaa_incomplete")
		.icon(() => Item.of("kubejs:incomplete_parts_box"))
		.content(() => [
			'kubejs:substrate',
			'kubejs:magenta_substrate',
			'kubejs:lime_substrate',
			'kubejs:culture_plate',
			'kubejs:incomplete_rectifier',
			'kubejs:incomplete_bearing',
			'kubejs:incomplete_planetary_gear',
			'kubejs:incomplete_differential',
			'kubejs:incomplete_cardan_joint',
			'kubejs:incomplete_diesel_engine',
			'kubejs:incomplete_large_diesel_engine',
			'kubejs:incomplete_huge_diesel_engine',
			'kubejs:incomplete_steam_engine',
			'kubejs:incomplete_alternator',
			'kubejs:incomplete_electric_motor',
			'kubejs:incomplete_electric_gear',
			'kubejs:incomplete_engine_piston',
			'kubejs:incomplete_andesite_box',
			'kubejs:incomplete_copper_box',
			'kubejs:incomplete_brass_box',
			'kubejs:incomplete_railway_box',
			'kubejs:incomplete_brass_hand',
			'kubejs:incomplete_iron_hand',
			'kubejs:incomplete_rocket_mechanism',
			'kubejs:incomplete_chargeable_battery',
			'kubejs:incomplete_disposable_battery',
			'kubejs:incomplete_culture_plate',
			'kubejs:incomplete_fluid',
			'kubejs:incomplete_can',
			'kubejs:incomplete_parts_box',
			'kubejs:incomplete_brass_hard_disk',
			'kubejs:incomplete_aluminum_hard_disk',
			'kubejs:incomplete_tin_hard_disk',
		])
		.displayName = Text.translatable("kubejs.creative_tab.incomplete")
})
StartupEvents.modifyCreativeTab("ad_astra:main", tab => {
	tab.remove([
		Item.of('ad_astra:tier_1_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
		Item.of('ad_astra:tier_2_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
		Item.of('ad_astra:tier_3_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
		Item.of('ad_astra:tier_4_rocket', '{BotariumData:{StoredFluids:[{Amount:0L,Fluid:"minecraft:empty"}]}}').strongNBT(),
	])
})
