JEIEvents.information(event=>{
    event.addItem("kubejs:unknown_prototype",[
        Text.translate('kubejs.jei_info.unknown_prototype.1'),
        Text.translate('kubejs.jei_info.unknown_prototype.2'),
        Text.translate('kubejs.jei_info.unknown_prototype.3'),
        Text.translate('kubejs.jei_info.unknown_prototype.4')
    ])
})
JEIEvents.hideItems(event => {
    event.hide([
        "createaddition:bioethanol_bucket",
        "createloveandwar:diesel_bucket",
        'createloveandwar:kerosene_bucket',
        'createloveandwar:ethylene_bucket',
        'createloveandwar:polymer_bucket',
        'createloveandwar:duraplas_bucket',
        "createloveandwar:propellant_sheet",
    ])
    event.hide([
        "createloveandwar:pistol_bullet_ap",
        "createloveandwar:rifle_bullet_ap",
        "createloveandwar:pistol_bullet_soft",
        "createloveandwar:rifle_bullet_soft",
        "createloveandwar:pistol_bullet",
        "createloveandwar:rifle_bullet",
        "createloveandwar:heavy_rifle_bullet",
        "createloveandwar:pistol_casing",
        "createloveandwar:rifle_casing",
        "createloveandwar:heavy_rifle_casing",
        "createloveandwar:steel_cup",
        "createloveandwar:filled_pistol_casing",
        "createloveandwar:filled_rifle_casing",
        "createloveandwar:filled_heavy_rifle_casing",
        "iceandfire:bestiary",
        "iceandfire:manuscript",
        "iceandfire:pixel_jar_empty",
        "iceandfire:pixel_jar_0",
        "iceandfire:pixel_jar_1",
        "iceandfire:pixel_jar_2",
        "iceandfire:pixel_jar_3",
        "iceandfire:pixel_jar_4",
        "create_sa:andesite_exoskeleton",
        "create_sa:andesite_jetpack",
        "create_sa:copper_exoskeleton",
        "create_sa:copper_jetpack",
        "create_sa:small_fueling_tank",
        "create_sa:medium_fueling_tank",
        "create_sa:large_fueling_tank",
        "create_sa:small_filling_tank",
        "create_sa:medium_filling_tank",
        "create_sa:large_filling_tank",
        'createloveandwar:diesel_bucket',
        'createloveandwar:kerosene_bucket',
        'createloveandwar:ethylene_bucket',
        'createloveandwar:polymer_bucket',
        'createloveandwar:duraplas_bucket',
        'createdieselgenerators:plant_oil_bucket',
        'ae2:facade'
    ])
})
JEIEvents.hideFluids(event => {
    event.hide([
        "createaddition:bioethanol",
        "createloveandwar:diesel",
        'createloveandwar:kerosene',
        'createloveandwar:ethylene',
        'createloveandwar:polymer',
        'createloveandwar:duraplas'
    ])
})
JEIEvents.addFluids(event => {
    event.add([
        "vintageimprovements:sulfur_dioxide",
        "vintageimprovements:sulfur_trioxide"
    ])
})
JEIEvents.addItems(event => {
    event.add([
        "create:copper_nugget",
        "create:iron_sheet"
    ])
})
JEIEvents.removeRecipes(event => {
    event.remove('create:item_application',
        [
            "dut_create:blaze_mycoplasma/blaze_burner_manual_only",
            "dut_create:deploying/crushing_wheel"
        ]
    )
    event.remove('create:emptying',
        [
            "create:empty_createaddition_bioethanol_bucket_of_createaddition_bioethanol"
        ]
    )
    event.remove('create:filling',
        [
            "create:fill_minecraft_bucket_with_createaddition_bioethanol"
        ]
    )
})