JEIEvents.hideItems(event => {
    event.hide([
        "createaddition:bioethanol_bucket",
        "createloveandwar:diesel_bucket",
        'createloveandwar:kerosene_bucket',
        'createloveandwar:ethylene_bucket',
        'createloveandwar:polymer_bucket',
        'createloveandwar:duraplas_bucket',
        "createloveandwar:propellant_sheet",
    ])
    event.hide([
        "createloveandwar:pistol_bullet_ap",
        "createloveandwar:rifle_bullet_ap",
        "createloveandwar:pistol_bullet_soft",
        "createloveandwar:rifle_bullet_soft",
        "createloveandwar:pistol_bullet",
        "createloveandwar:rifle_bullet",
        "createloveandwar:heavy_rifle_bullet",
        "createloveandwar:pistol_casing",
        "createloveandwar:rifle_casing",
        "createloveandwar:heavy_rifle_casing",
        "createloveandwar:steel_cup",
        "createloveandwar:filled_pistol_casing",
        "createloveandwar:filled_rifle_casing",
        "createloveandwar:filled_heavy_rifle_casing",
        "iceandfire:bestiary",
        "iceandfire:manuscript",
        "iceandfire:pixel_jar_empty",
        "iceandfire:pixel_jar_0",
        "iceandfire:pixel_jar_1",
        "iceandfire:pixel_jar_2",
        "iceandfire:pixel_jar_3",
        "iceandfire:pixel_jar_4",
        "create_sa:andesite_exoskeleton",
        "create_sa:andesite_jetpack",
        "create_sa:copper_exoskeleton",
        "create_sa:copper_jetpack",
        "create_sa:small_fueling_tank",
        "create_sa:medium_fueling_tank",
        "create_sa:large_fueling_tank",
        "create_sa:small_filling_tank",
        "create_sa:medium_filling_tank",
        "create_sa:large_filling_tank",
        'createloveandwar:diesel_bucket',
        'createloveandwar:kerosene_bucket',
        'createloveandwar:ethylene_bucket',
        'createloveandwar:polymer_bucket',
        'createloveandwar:duraplas_bucket',
        'createdieselgenerators:plant_oil_bucket',
        'ae2:facade',
        'kubejs:substrate',
        'kubejs:magenta_substrate',
        'kubejs:lime_substrate',
        'kubejs:incomplete_rectifier',
        'kubejs:incomplete_bearing',
        'kubejs:incomplete_planetary_gear',
        'kubejs:incomplete_differential',
        'kubejs:incomplete_cardan_joint',
        'kubejs:incomplete_diesel_engine',
        'kubejs:incomplete_large_diesel_engine',
        'kubejs:incomplete_huge_diesel_engine',
        'kubejs:incomplete_steam_engine',
        'kubejs:incomplete_alternator',
        'kubejs:incomplete_electric_motor',
        'kubejs:incomplete_electric_gear',
        'kubejs:incomplete_engine_piston',
        'kubejs:incomplete_andesite_box',
        'kubejs:incomplete_copper_box',
        'kubejs:incomplete_brass_box',
        'kubejs:incomplete_railway_box',
        'kubejs:incomplete_brass_hand',
        'kubejs:incomplete_iron_hand',
        'kubejs:incomplete_rocket_mechanism',
        'kubejs:incomplete_chargeable_battery',
        'kubejs:incomplete_disposable_battery',
        'kubejs:incomplete_culture_plate',
        'kubejs:incomplete_fluid',
        'kubejs:incomplete_can',
        'kubejs:incomplete_parts_box',
        'kubejs:incomplete_brass_hard_disk',
        'kubejs:incomplete_aluminum_hard_disk',
        'kubejs:incomplete_tin_hard_disk',
    ])
})
JEIEvents.hideFluids(event => {
    event.hide([
        "createaddition:bioethanol",
        "createloveandwar:diesel",
        'createloveandwar:kerosene',
        'createloveandwar:ethylene',
        'createloveandwar:polymer',
        'createloveandwar:duraplas'
    ])
})
JEIEvents.addFluids(event => {
    event.add([
        "vintageimprovements:sulfur_dioxide",
        "vintageimprovements:sulfur_trioxide"
    ])
})
JEIEvents.addItems(event => {
    event.add([
        "create:copper_nugget",
        "create:iron_sheet"
    ])
})
JEIEvents.removeRecipes(event => {
    event.remove('create:item_application',
        [
            "dut_create:blaze_mycoplasma/blaze_burner_manual_only",
            "dut_create:deploying/crushing_wheel"
        ]
    )
    event.remove('create:deploying',
        [
            "dut_create:andesite_alloy_manual_only_using_deployer"
        ]
    )
    event.remove('create:emptying',
        [
            "create:empty_createaddition_bioethanol_bucket_of_createaddition_bioethanol"
        ]
    )
    event.remove('create:filling',
        [
            "create:fill_minecraft_bucket_with_createaddition_bioethanol"
        ]
    )
})