ServerEvents.recipes(event => {
  //event.custom().id("dut_create:")
  //event.custom().id("dut_create:")

    //event.remove({ id:"create:fill_minecraft_bucket_with_ad_astra_oil"})
    event.remove({id:"ad_astra:blasting/gold_ingot_from_blasting_venus_gold_ore" })
    event.remove({id:"ad_astra:blasting/diamond_from_blasting_mars_diamond_ore" })
    event.remove({id:"ad_astra:blasting/diamond_from_blasting_venus_diamond_ore" })
    event.remove({id:"ad_astra:blasting/coal_from_blasting_venus_coal_ore" })
    event.remove({id:"ad_astra:blasting/coal_from_blasting_glacio_coal_ore" })
    event.remove({id:"ad_astra:blasting/iron_ingot_from_blasting_glacio_iron_ore" })
    event.remove({id:"ad_astra:blasting/iron_ingot_from_blasting_mars_iron_ore" })
    event.remove({id:"ad_astra:blasting/iron_ingot_from_blasting_mercury_iron_ore" })
    event.remove({id:"ad_astra:blasting/iron_ingot_from_blasting_moon_iron_ore" })
    event.remove({id:"ad_astra:blasting/copper_ingot_from_blasting_glacio_copper_ore" })
    event.remove({id:"ad_astra:blasting/lapis_lazuli_from_blasting_glacio_lapis_ore" })
    event.remove({id:"ad_astra:blasting/cheese_from_blasting_moon_cheese_ore" })
    event.remove({id:"ad_astra:blasting/ice_shard_from_blasting_moon_ice_shard_ore" })
    event.remove({id:"ad_astra:blasting/ice_shard_from_blasting_deepslate_ice_shard_ore" })
    event.remove({id:"ad_astra:blasting/ice_shard_from_blasting_mars_ice_shard_ore" })
    event.remove({id:"ad_astra:blasting/ice_shard_from_blasting_glacio_ice_shard_ore" })
    event.remove({id:"ad_astra:smelting/cheese_from_smelting_moon_cheese_ore" })
    event.remove({id:"ad_astra:smelting/ice_shard_from_smelting_deepslate_ice_shard_ore" })
    event.remove({id:"ad_astra:smelting/ice_shard_from_smelting_glacio_ice_shard_ore" })
    event.remove({id:"ad_astra:smelting/ice_shard_from_smelting_mars_ice_shard_ore" })
    event.remove({id:"ad_astra:smelting/ice_shard_from_smelting_moon_ice_shard_ore" })
    event.remove({id:"ad_astra:smelting/coal_from_smelting_glacio_coal_ore" })
    event.remove({id:"ad_astra:smelting/coal_from_smelting_venus_coal_ore" })
    event.remove({id:"ad_astra:smelting/calorite_ingot_from_smelting_deepslate_calorite_ore" })
    event.remove({id:"ad_astra:smelting/calorite_ingot_from_smelting_raw_calorite" })
    event.remove({id:"ad_astra:smelting/calorite_ingot_from_smelting_venus_calorite_ore" })
    event.remove({id:"ad_astra:smelting/ostrum_ingot_from_smelting_deepslate_ostrum_ore" })
    event.remove({id:"ad_astra:smelting/ostrum_ingot_from_smelting_mars_ostrum_ore" })
    event.remove({id:"ad_astra:smelting/ostrum_ingot_from_smelting_raw_ostrum" })
    event.remove({id:"ad_astra:smelting/iron_ingot_from_smelting_glacio_iron_ore" })
    event.remove({id:"ad_astra:smelting/iron_ingot_from_smelting_mars_iron_ore" })
    event.remove({id:"ad_astra:smelting/iron_ingot_from_smelting_mercury_iron_ore" })
    event.remove({id:"ad_astra:smelting/iron_ingot_from_smelting_moon_iron_ore" })
    event.remove({id:"ad_astra:smelting/gold_ingot_from_smelting_venus_gold_ore" })
    event.remove({id:"ad_astra:smelting/diamond_from_smelting_mars_diamond_ore" })
    event.remove({id:"ad_astra:smelting/diamond_from_smelting_venus_diamond_ore" })
    event.remove({id:"ad_astra:smelting/lapis_lazuli_from_smelting_glacio_lapis_ore" })
    event.remove({id:"ad_astra:smelting/glacio_stone_from_smelting_glacio_cobblestone" })
    event.remove({id:"ad_astra:smelting/cracked_glacio_stone_bricks_from_smelting_glacio_stone_bricks" })
    event.remove({id:"ad_astra:smelting/mars_stone_from_smelting_mars_cobblestone" })
    event.remove({id:"ad_astra:smelting/cracked_mars_stone_bricks_from_smelting_mars_stone_bricks" })
    event.remove({id:"ad_astra:smelting/venus_stone_from_smelting_venus_cobblestone" })
    event.remove({id:"ad_astra:smelting/cracked_venus_sandstone_bricks_from_smelting_venus_sandstone_bricks" })
    event.remove({id:"ad_astra:smelting/cracked_venus_stone_bricks_from_smelting_venus_stone_bricks" })
    event.remove({id:"ad_astra:smelting/cracked_permafrost_bricks_from_smelting_permafrost_bricks" })
    event.remove({id:"ad_astra:smelting/copper_ingot_from_smelting_glacio_copper_ore" })
    event.remove({id:"ad_astra:smelting/mercury_stone_from_smelting_mercury_cobblestone" })
    event.remove({id:"ad_astra:smelting/cracked_mercury_stone_bricks_from_smelting_mercury_stone_bricks" })
})