ServerEvents.recipes(event => {
  //event.custom().id("dut_create:")
  //event.custom().id("dut_create:")

  //event.remove({ id:"create:fill_minecraft_bucket_with_ad_astra_oil"})
  event.remove({ id: "create:crushing/coal_ore" })
  event.remove({ id: "create:crushing/gold_ore" })
  event.remove({ id: "create:crushing/diamond_ore" })
  event.remove({ id: "create:crushing/lapis_ore" })
  event.remove({ id: "create:crushing/copper_ore" })
  event.remove({ id: "create:crushing/emerald_ore" })
  event.remove({ id: "create:crushing/redstone_ore" })
  event.remove({ id: "create:crushing/iron_ore" })
  event.remove({ id: "create:crushing/deepslate_coal_ore" })
  event.remove({ id: "create:crushing/deepslate_copper_ore" })
  event.remove({ id: "create:crushing/deepslate_diamond_ore" })
  event.remove({ id: "create:crushing/deepslate_emerald_ore" })
  event.remove({ id: "create:crushing/deepslate_gold_ore" })
  event.remove({ id: "create:crushing/deepslate_iron_ore" })
  event.remove({ id: "create:crushing/deepslate_lapis_ore" })
  event.remove({ id: "create:crushing/deepslate_redstone_ore" })
  event.remove({ id: "create:crushing/glowstone" })
  event.remove({ id: "create:crushing/iron_horse_armor" })
  event.remove({ id: "create:crushing/golden_horse_armor" })
  event.remove({ id: "create:crushing/diamond_horse_armor" })
  event.remove({ id: "create:crushing/leather_horse_armor" })
  event.remove({ id: "createloveandwar:crushing/sulphur_ore" })
  event.remove({ id: "createloveandwar:crushing/deepslate_sulphur_ore" })
  event.remove({ id: "create:crushing/nether_gold_ore" })
  event.remove({ id: "create:crushing/nether_quartz_ore" })
  event.remove({ id: "create:crushing/blaze_rod" })
  event.remove({ id: "create:crushing/gilded_blackstone" })
  event.remove({ id: "createloveandwar:crushing/exp_from_gunsmith_parts" })
  event.remove({ id: "create:milling/compat/supplementaries/flax" })
  event.remove({ id: "create_enchantment_industry:compacting/experience_block_from_slime_ball" })
  event.remove({ id: "create_enchantment_industry:compacting/experience_block_from_honeycomb" })
  event.remove({ id: "createbigcannons:compacting/forge_nethersteel_nugget" })
  event.remove({ id: "createbigcannons:compacting/forge_cast_iron_nugget" })
  event.remove({ id: "minecraft:netherite_scrap" })
  event.remove({ id: "minecraft:netherite_scrap_from_blasting" })
})