ServerEvents.recipes(event => {
  //event.custom().id("dut_create:")
  //event.custom().id("dut_create:")

  //event.remove({ id:"create:fill_minecraft_bucket_with_ad_astra_oil"})
  event.remove({ type: "minecraft:blasting", input: "minecraft:raw_iron" })
  event.remove({ type: "minecraft:blasting", input: "minecraft:raw_gold" })
  event.remove({ type: "minecraft:blasting", input: "minecraft:raw_copper" })
  event.remove({ type: "minecraft:blasting", input: "create:raw_zinc" })
  event.remove({ type: "minecraft:blasting", input: "iceandfire:raw_silver" })


  event.remove({ output: 'ad_astra:sky_stone' })
  function killFuckingCrushing(recipeID) {
    event.remove({ id: 'create:crushing/' + recipeID })
  }
  event.remove({ id: 'vintageimprovements:crushing/basalt_recycling' })
  event.remove({ id: 'vintageimprovements:crushing/basalt' })
  killFuckingCrushing('raw_iron')
  killFuckingCrushing('raw_gold')
  killFuckingCrushing('raw_copper')
  killFuckingCrushing('raw_zinc')
  killFuckingCrushing('raw_silver')
  killFuckingCrushing('venus_calorite_ore')
  killFuckingCrushing('venus_gold_ore')
  killFuckingCrushing('venus_coal_ore')
  killFuckingCrushing('venus_diamond_ore')
  killFuckingCrushing('mercury_iron_ore')
  killFuckingCrushing('mars_diamond_ore')
  killFuckingCrushing('mars_ice_shard_ore')
  killFuckingCrushing('mars_ostrum_ore')
  killFuckingCrushing('mars_iron_ore')
    event.remove({id:"create:milling/venus_sandstone" })
    event.remove({id:"create:crushing/glacio_copper_ore" })
    event.remove({id:"create:crushing/glacio_ice_shard_ore" })
    event.remove({id:"create:crushing/glacio_iron_ore" })
    event.remove({id:"create:crushing/glacio_lapis_ore" })
  event.remove({ id: "create:crushing/glacio_coal_ore" })
  event.remove({ id: "create:crushing/deepslate_ostrum_ore" })
  event.remove({ id: "create:crushing/moon_cheese_ore" })
  event.remove({ id: "create:crushing/moon_desh_ore" })
  event.remove({ id: "create:crushing/moon_ice_shard_ore" })
  event.remove({ id: "create:crushing/deepslate_ice_shard_ore" })
  event.remove({ id: "create:crushing/deepslate_desh_ore" })
  event.remove({ id: "create:crushing/moon_iron_ore" })
  event.remove({ id: "create:crushing/venus_calorite_ore" })
  event.remove({ id: "create:crushing/deepslate_calorite_ore" })
  event.remove({ mod: 'ad_astra', output: "ad_astra:ostrum_ingot", not: { type: 'crafting_shaped' }, not: { type: 'crafting_shapeless' } })
  event.remove({ mod: 'ad_astra', output: "ad_astra:desh_ingot", not: { type: 'crafting_shaped' }, not: { type: 'crafting_shapeless' } })
  event.remove({ mod: 'ad_astra', output: "ad_astra:calorite_ingot", not: { type: 'crafting_shaped' }, not: { type: 'crafting_shapeless' } })
})