
#Recipe Time Normalization
[normalization]
	#Set the Deployer’s full-speed processing time to 5 ticks.
	deployer = true
	#Set the Crushing Wheel’s full-speed processing time equals to recipe time and default value to 30 ticks.
	crushing_wheel = true
	#Set the Item Drain's rolling time to 10 ticks and recipe time to 10 ticks.
	item_drain = true
	#Set the Millstone's full-speed processing time equals to recipe time.
	millstone = true
	#Set the Mechanical Mixer's default full-speed processing time to 15 ticks.
	mixer = true
	#Set the Mechanical Press's full-speed processing time to 10 ticks.
	press = true
	#Set the Mechanical Saw's full-speed processing time to 10 ticks each bulk.
	saw = true
	#Set the Spout's processing time to 20 ticks.
	spout = true
	#Set the Chute's default transport time to 5 ticks.
	chute = true
	#Multiply the fluid network transfer speed by 8.
	pump = true
	#Set the Depot item movement animation duration to 5 ticks.
	depot = true
	#Set the Valve state toggle duration at full speed to 1 tick.
	valve = true

#Behaviour Tweaks
[tweaks]
	#Allows funnels to extract items positioned exactly at the center of a belt.
	#Previously, funnels could only extract items past the center.
	#When a opposing funnel blocks items at the center, all side-facing belt funnels stop extracting, which is unintuitive.
	belt_funnel_detection_tweak = true
	#Set the spout's fluid capacity to 2000 mB.
	spout_double_capacity = true
	#Prevent Diagonal Chutes from interacting with containers below.
	#Because visually, Diagonal Chutes have no opening at the bottom.
	no_chute_leaking = true
	#Allow all players flying.
	always_allow_flying = true
	#Allow rotation for blocks without a custom rotate implementation.
	#Many mod authors do not override rotate and mirror when adding directional blocks.
	#As a result, vanilla structure block placement and Create schematic printing are unable to correctly rotate these blocks.
	#Enabling this feature automatically detects common facing properties and applies rotation/mirror.
	heuristic_rotation = true
	#Prevent the depot from dropping overflow items.
	#For example when it accumulates too many processing outputs.
	#Or when an Ejector cannot merge received item stacks.
	no_depot_overflow_drop = true
	#Allow pumps to replace any flowing fluid, ignoring the fluid type.
	replace_any_flowing_fluid = true
	#Prevent harvester from consuming seed when replanting.
	harvester_not_consume_seed = true
	#When players are in the air or water, they will no longer be subject to a five-time increase in digging time penalty
	disable_dig_speed_penalty = true
	#Prevent forge initializing the item capabilities when comparing item stacks.
	dont_compare_item_capability = true
	#PSIs on trains are now only activated when the train arrives at a station.
	better_psi_on_carriage = true
	#Player won't drown underwater.
	player_can_breath_underwater = true
	#Prevents players from automatically exiting flight mode when touching the ground.
	keep_flying_on_ground = true
	#Make super glue as convenient as honey glue from Aeronautic.
	hachimi_glue = true

