Ponder.tags((event) => {
    event.createTag(
      "kubejs:matrix",
      "kubejs:matrix_2",
      "信息素矩阵",
      "对信息素的矩阵结构进行加工"
    );
    event.createTag(
      "kubejs:block_crafting",
      "create:schematic_and_quill",
      "多方块结构合成",
      "在世界中建造特定结构来进行合成"
    );
    event.createTag(
      "kubejs:machine_and_multiblock",
      "kubejs:differential",
      "建造机器与多方块结构",
      "一些机器和多方块结构的简单教学。这里仅提供示范而非最优解(事实上，大多数机器不存在全局意义下的最优解，需要根据实际情况进行选择和设计！)"
    );
    event.createTag(
      "kubejs:create_basic_automatic",
      "kubejs:productivity_module",
      "基础自动化",
      "一些自动化内容的简单教学。这里仅提供示范而非最优解(事实上，大多数机器不存在全局意义下的最优解，需要根据实际情况进行选择和设计！)"
    );
    event.createTag(
      "kubejs:block_filling_conway",
      "minecraft:red_mushroom_block",
      "方块注液-催化生长",
      "通过方块注液令菌类生长"
    );
    event.createTag(
      "kubejs:block_filling_basic",
      "create:spout",
      "方块注液-方块转化",
      "通过方块注液将方块转化为其它种类的方块"
    );
    event.createTag(
      "kubejs:block_filling_item",
      "create:spout",
      "方块注液-物品转化",
      "通过方块注液将方块转化为物品"
    );
    event.createTag(
      "kubejs:block_filling_extra_item",
      "create:spout",
      "方块注液-物品生产",
      "通过方块注液让方块额外产出物品"
    );
    event.createTag(
      "kubejs:entity_filling",
      "create:spout",
      "生物注液",
      "通过注液让生物额外产出物品"
    );
  });