StartupEvents.registry('block', event => {
	//Syntax : event.create("namespace:block_id", "custommachinery").machine("namespace:machine_id)
	event.create("kubejs:hydropress", "custommachinery")
		.machine("dut:hydropress")
	event.create("kubejs:launch_pad_controller", "custommachinery")
		.machine("dut:launch_pad_controller")
	event.create("kubejs:condenser", "custommachinery")
		.machine("dut:condenser")
	event.create("kubejs:alloy_furnace", "custommachinery")
		.machine("dut:alloy_furnace")
	event.create("kubejs:huge_crusher", "custommachinery")
		.machine("dut:huge_crusher")
	event.create("kubejs:shaft_furnace", "custommachinery")
		.machine("dut:shaft_furnace")
	event.create("kubejs:infinity_fetching_pool", "custommachinery")
		.machine("dut:infinity_fetching_pool")
	event.create("kubejs:electrolytic_cell", "custommachinery")
		.machine("dut:electrolytic_cell")
	event.create("kubejs:steam_generator", "custommachinery")
		.machine("dut:steam_generator")
	event.create("kubejs:assembling_machine", "custommachinery")
		.machine("dut:assembling_machine")
	event.create("kubejs:construction_station", "custommachinery")
		.machine("dut:construction_station")
	event.create("kubejs:large_difference_engine", "custommachinery")
		.machine("dut:large_difference_engine")
	event.create("kubejs:electron_tube_computer", "custommachinery")
		.machine("dut:electron_tube_computer")
	event.create("kubejs:satellite_station", "custommachinery")
		.machine("dut:satellite_station")
	event.create("kubejs:airdrop_station", "custommachinery")
		.machine("dut:airdrop_station")
	event.create("kubejs:blueprint_builder", "custommachinery")
		.machine("dut:blueprint_builder")
	event.create("kubejs:blasting_compressor", "custommachinery")
		.machine("dut:blasting_compressor")
	event.create("kubejs:covariant_reactor", "custommachinery")
		.machine("dut:covariant_reactor")
	event.create("kubejs:space_elevator_controller", "custommachinery")
		.machine("dut:space_elevator_controller")
	event.create("kubejs:electro_hydro_resonant_tower", "custommachinery")
		.machine("dut:electro_hydro_resonant_tower")
	event.create("kubejs:planting_tower", "custommachinery")
		.machine("dut:planting_tower")
	event.create("kubejs:trading_station", "custommachinery")
		.machine("dut:trading_station")


})