// priority: 1024

// 与 /kubejs/data/dut/upgrades/ 下的 JSON 文件对应
const upgradesData = [
  {
    item: 'kubejs:productivity_module',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:shaft_furnace',
      'dut:satellite_station',
      'dut:steam_generator',
      'dut:electro_hydro_resonant_tower',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.925,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.05,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.05,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.975,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.975,
      },
    ],
  },
  {
    item: 'kubejs:productivity_module_2',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:shaft_furnace',
      'dut:steam_generator',
      'dut:electro_hydro_resonant_tower',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.875,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.075,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.075,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.9,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.9,
      },
    ],
  },
  {
    item: 'kubejs:productivity_module_3',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:shaft_furnace',
      'dut:satellite_station',
      'dut:steam_generator',
      'dut:electro_hydro_resonant_tower',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.75,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.125,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.125,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.8,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 0.8,
      },
    ],
  },
  {
    item: 'kubejs:speed_module',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:satellite_station',
      'dut:shaft_furnace',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.875,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.15,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.15,
      },
    ],
  },
  {
    item: 'kubejs:speed_module_2',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:shaft_furnace',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.75,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.25,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.25,
      },
    ],
  },
  {
    item: 'kubejs:speed_module_3',
    machines: [
      'dut:electron_tube_computer',
      'dut:large_difference_engine',
      'dut:alloy_furnace',
      'dut:assembling_machine',
      'dut:condenser',
      'dut:construction_station',
      'dut:culture_bin',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:launch_pad_controller',
      'dut:shaft_furnace',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:speed',
        mode: 'input',
        min: 5,
        operation: 'multiplication',
        modifier: 0.5,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.4,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 1,
        operation: 'multiplication',
        modifier: 1.4,
      },
    ],
  },
  {
    item: 'kubejs:efficiency_module',
    machines: [
      'dut:electron_tube_computer',
      'dut:assembling_machine',
      'dut:construction_station',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:steam_generator',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 100,
        operation: 'multiplication',
        modifier: 0.95,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 600,
        operation: 'multiplication',
        modifier: 0.95,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.05,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.05,
      },
    ],
  },
  {
    item: 'kubejs:efficiency_module_2',
    machines: [
      'dut:electron_tube_computer',
      'dut:assembling_machine',
      'dut:construction_station',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:steam_generator',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 100,
        operation: 'multiplication',
        modifier: 0.875,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 600,
        operation: 'multiplication',
        modifier: 0.875,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.075,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.075,
      },
    ],
  },
  {
    item: 'kubejs:efficiency_module_3',
    machines: [
      'dut:electron_tube_computer',
      'dut:assembling_machine',
      'dut:construction_station',
      'dut:electrolytic_cell',
      'dut:infinity_fetching_pool',
      'dut:steam_generator',
    ],
    modifiers: [
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'input',
        min: 100,
        operation: 'multiplication',
        modifier: 0.75,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'input',
        min: 600,
        operation: 'multiplication',
        modifier: 0.75,
      },
      {
        requirement: 'custommachinery:energy_per_tick',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.125,
      },
      {
        requirement: 'custommachinery:energy',
        mode: 'output',
        min: 1,
        operation: 'multiplication',
        modifier: 1.125,
      },
    ],
  },
];
