StartupEvents.registry('item', event => {
    event.create('yeast')
    event.create('chromatic_protozoa')
    event.create('peat_protozoa')
    event.create('metal_protozoa')
    event.create('resonant_bacteria')
    event.create('useless_bacteria')
    event.create('blaze_chlamydia').burnTime(163840)
    event.create('blaze_mycoplasma').burnTime(1600)
    event.create('blaze_wart')
    event.create('cheese_moonalgae')
    event.create('phantom_fungus')
    event.create('mycetozoan').food(food => {
        food.hunger(3)
        food.saturation(3)
        food.effect("minecraft:unluck", 36000, 4, 1)
    })
    event.create('myxomycetes_halophila')
    event.create('empty_culture_plate')
    event.create('culture_plate')
    event.create('pasteurized_culture_plate')
    event.create('strophar_cap_piece')
    event.create('strophar_stem_piece')
    event.create('aeronos_cap_piece')
    event.create('aeronos_stem_piece')
    event.create('red_mushroom_cap_piece')
    event.create('brown_mushroom_cap_piece')
    event.create('stem_silk')
    //event.create('culture_plate').texture('kubejs:item/culture_plate')
    //event.create('pasteurized_culture_plate').texture('kubejs:item/pasteurized_culture_plate')
})

