Platform.mods.kubejs.name = 'The Brass Concerto'
StartupEvents.registry('item', event => {
    //event.create('')
    event.create('brass_hard_disk').maxDamage(1024)
    event.create('aluminum_hard_disk').maxDamage(1024)
    event.create('tin_hard_disk').maxDamage(1024)
    event.create('navigate_data_empty')
    event.create('navigate_data_earth')
    event.create('navigate_data_earth_orbit')
    event.create('navigate_data_moon')
    event.create('navigate_data_moon_orbit')
    event.create('navigate_data_mars')
    event.create('navigate_data_mars_orbit')
    event.create('navigate_data_venus')
    event.create('navigate_data_venus_orbit')
    event.create('navigate_data_mercury')
    event.create('navigate_data_mercury_orbit')
    event.create('navigate_data_glacio')
    event.create('navigate_data_glacio_orbit')
    event.create('navigate_data_slimeria')
    event.create('navigate_data_slimeria_orbit')
})
StartupEvents.registry('block', event => {
    event.create('difference_engine', "cardinal")
        .transparent(true)
        .viewBlocking(true)
        .tagBlock('create:wrench_pickup')
        .noValidSpawns(true)
        .defaultCutout()
        .box(0, 0, 0, 16, 30, 16, true)
})
