//熔融金属
StartupEvents.registry('fluid', event => {
    //熔融氧化铝
    event.create('fused_alumina')
        .thickTexture(0xFFA8F0)
    //熔融铝
    event.create('aluminum')
        .thickTexture(0xDEDEF0)
    //熔融戴斯
    event.create('desh')
        .thickTexture(0xFF9E00)
    //熔融锡
    event.create('tin')
        .thickTexture(0xC5E3FF)
    //熔融银
    event.create('silver')
        .thickTexture(0xD4FFF9)
    //熔融锌
    event.create('zinc')
        .thickTexture(0x0EFF97)
    //熔融金
    event.create('gold')
        .thickTexture(0xFFF860)
    //熔融铁
    event.create('iron')
        .thickTexture(0xFFD8D8)
    //熔融铜
    event.create('copper')
        .thickTexture(0xFF6C40)
    //熔融黄铜
    event.create('brass')
        .thickTexture(0xFFC800)
    //熔融工业铁
    event.create('industrial_iron')
        .thickTexture(0x95A1FF)
    //半成品钢
    event.create('incomplete_steel')
        .thinTexture(0xFFEBBB)
    //半成品钢-1
    //event.create('incomplete_steel_1').thickTexture(0xFFBBAB)
})
//液体
StartupEvents.registry('fluid', event => {
    //绿色孢子
    event.create('green_spore')
        .thinTexture(0xDFFF00)
    //蓝色孢子
    event.create('blue_spore')
        .thinTexture(0x95FFD8)
    //红色孢子
    event.create('red_spore')
        .thinTexture(0xFFBFDD)
    //空果孢子
    event.create('aeronos_spore')
        .thickTexture(0x4BFFA9)
    //孑孓孢子
    event.create('strophar_spore')
        .thickTexture(0xFF8FCD)
    //棕色蘑菇孢子
    event.create('brown_mushroom_spore')
        .thinTexture(0xFFC06F)
    //红色蘑菇孢子
    event.create('red_mushroom_spore')
        .thinTexture(0xFF7F4C)
    //奇异孢子
    event.create('singular_spore')
        .thickTexture(0xFFC46C)
    //史莱利亚大气
    event.create('slimeria_air_fluid')
        .thinTexture(0xFFC46C)
    //史莱姆凝胶
    event.create('slime_colloid')
        .thickTexture(0xB8FF5E)
    //冷冻剂
    event.create('cryogen')
        .thinTexture(0x00A5E4)
    //液态空气
    event.create('air_fluid')
        .thinTexture(0xAAAAAA)
    //液态下界空气
    event.create('nether_air_fluid')
        .thickTexture(0xBBAAAA)
    //液态末地空气
    event.create('end_air_fluid')
        .thickTexture(0xBBAABB)
    //硝酸
    event.create('nitric_acid')
        .thinTexture(0xC25A34)
    //氮肥
    event.create('nitrogen_fertilizer')
        .thinTexture(0xFFEB63)
    //聚乙烯
    event.create('polymer')
        .thickTexture(0xAFFFF4)
    //聚氯乙烯
    event.create('duraplas')
        .thickTexture(0xF9C6FF)
    //盐水
    event.create('saline_water')
        .thinTexture(0x62DEFF)
    //NaOH
    event.create('caustic_soda')
        .thickTexture(0xFFD6C4)
    //盐酸
    event.create('muriatic_acid')
        .thinTexture(0xB3FF00)
    //润滑油
    event.create('lube_oil')
        .thinTexture(0x00EE67)
    //钻井液
    event.create('drilling_fluid')
        .thickTexture(0xFF57BB)
    //精炼石油
    event.create('refined_oil')
        .thinTexture(0x5C0C00)
    //异彩废料
    event.create('chromatic_waste')
        .thickTexture(0xA70083)
        .noBlock()
})
//气体
StartupEvents.registry('fluid', event => {
    //氢气
    event.create('hydrogen')
        .thinTexture(0x8BD4FF)
        .gaseous()
    //氧气
    event.create('oxygen')
        .thinTexture(0xF8FFEE)
        .gaseous()
    //氮气
    event.create('nitrogen')
        .thinTexture(0xFF7E5A)
        .gaseous()
    //二氧化氮
    event.create('nitrogen_dioxide')
        .thinTexture(0xE06040)
        .gaseous()
    //氨
    event.create('ammonia')
        .thickTexture(0xFFD5AC)
        .gaseous()
    //氯气
    event.create('chlorine')
        .thinTexture(0xDFFF21)
        .gaseous()
    //二氧化碳
    event.create('carbon_dioxide')
        .thickTexture(0xCCCCCC)
        .noBlock()
        .gaseous()
    //天然气
    event.create('natural_gas')
        .thickTexture(0xC7FFFA)
        .gaseous()
    //乙烯
    event.create('ethylene')
        .thinTexture(0xE5FFBD)
        .gaseous()
    //加压蒸汽
    event.create('pressurized_steam')
        .thinTexture(0xFFEFFF)
        .gaseous()
})
//无桶&无贴图
StartupEvents.registry('fluid', event => {
    //史莱姆币
    event.create('slime_coin')
        .thickTexture(0xFFF860)
        .noBlock()
        .noBucket()
    //TiB
    event.create('tebibyte')
        .thinTexture(0x666666)
        .noBlock()
        .noBucket()
    //GiB
    event.create('gibibyte')
        .thinTexture(0x777777)
        .noBlock()
        .noBucket()
    //MiB
    event.create('mebibyte')
        .thinTexture(0x888888)
        .noBlock()
        .noBucket()
    //KiB
    event.create('kibibyte')
        .thinTexture(0x999999)
        .noBlock()
        .noBucket()
    //液压流体
    event.create('hydrofluid')
        .thinTexture(0xAAAAFF)
        .noBlock()
        .noBucket()
    //火箭燃料
    event.create('rocket_fuel')
        .thickTexture(0xEEEEEE)
        .noBlock()
        .gaseous()
        .noBucket()
    //可乐原浆
    event.create('cola_puree')
        .thickTexture(0x6D2700)
    //史莱姆可乐
    event.create('slime_cola')
        .thinTexture(0x7E2800)
    //超热蒸汽
    event.create('superheated_steam')
        .thinTexture(0xFFFFFF)
        .gaseous()
        .noBucket()
    //电流体
    event.create('electro_hydro')
        .thickTexture(0x6AFFEE)
        .noBucket()
    //协变热
    event.create('covariant_heat')
        .thickTexture(0xFF6611)
        .noBucket()
})