StartupEvents.registry('item', event => {
    event.create('lapis_plate')
    event.create('silicon_plate')
    event.create('polymer_ingot')
    event.create('polymer_sheet')
    event.create('duraplas_ingot')
    event.create('duraplas_sheet')
    event.create('industrial_iron_nugget')
    event.create('industrial_iron_ingot')
    event.create('industrial_iron_sheet')
    event.create('raw_tin')
    event.create('tin_nugget')
    event.create('tin_ingot')
    event.create('tin_sheet')
    event.create('diorite_alloy')
    event.create('granite_alloy')
    event.create('aluminite')
    event.create('aluminite_powder')
    event.create('aluminum_slag')
    event.create('aluminum_ingot')
    event.create('aluminum_sheet')
})

StartupEvents.registry('block', event => {
    event.create('tin_block')
        .requiresTool(true)
        .fullBlock(true)
        .stoneSoundType()
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')

    event.create('aluminum_block')
        .requiresTool(true)
        .fullBlock(true)
        .stoneSoundType()
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
})
