ServerEvents.recipes(event => {
    //
    const EmptyingFluidFilter = [
        "minecraft:air",
        "minecraft:void_air",
        "minecraft:cave_air",
        "kubejs:oxygen[level=1]",
        "kubejs:oxygen[level=2]",
        "kubejs:oxygen[level=3]",
        "kubejs:oxygen[level=4]",
        "kubejs:oxygen[level=5]",
        "kubejs:oxygen[level=6]",
        "kubejs:oxygen[level=7]",
        "kubejs:oxygen[level=8]",
        "kubejs:oxygen[level=9]",
        "kubejs:oxygen[level=10]",
        "kubejs:oxygen[level=11]",
        "kubejs:oxygen[level=12]",
        "kubejs:oxygen[level=13]",
        "kubejs:oxygen[level=14]",
        "kubejs:oxygen[level=15]",
        "kubejs:hydrogen[level=1]",
        "kubejs:hydrogen[level=2]",
        "kubejs:hydrogen[level=3]",
        "kubejs:hydrogen[level=4]",
        "kubejs:hydrogen[level=5]",
        "kubejs:hydrogen[level=6]",
        "kubejs:hydrogen[level=7]",
        "kubejs:hydrogen[level=8]",
        "kubejs:hydrogen[level=9]",
        "kubejs:hydrogen[level=10]",
        "kubejs:hydrogen[level=11]",
        "kubejs:hydrogen[level=12]",
        "kubejs:hydrogen[level=13]",
        "kubejs:hydrogen[level=14]",
        "kubejs:hydrogen[level=15]",
        "kubejs:nitrogen_dioxide[level=1]",
        "kubejs:nitrogen_dioxide[level=2]",
        "kubejs:nitrogen_dioxide[level=3]",
        "kubejs:nitrogen_dioxide[level=4]",
        "kubejs:nitrogen_dioxide[level=5]",
        "kubejs:nitrogen_dioxide[level=6]",
        "kubejs:nitrogen_dioxide[level=7]",
        "kubejs:nitrogen_dioxide[level=8]",
        "kubejs:nitrogen_dioxide[level=9]",
        "kubejs:nitrogen_dioxide[level=10]",
        "kubejs:nitrogen_dioxide[level=11]",
        "kubejs:nitrogen_dioxide[level=12]",
        "kubejs:nitrogen_dioxide[level=13]",
        "kubejs:nitrogen_dioxide[level=14]",
        "kubejs:nitrogen_dioxide[level=15]",
        "kubejs:chlorine[level=1]",
        "kubejs:chlorine[level=2]",
        "kubejs:chlorine[level=3]",
        "kubejs:chlorine[level=4]",
        "kubejs:chlorine[level=5]",
        "kubejs:chlorine[level=6]",
        "kubejs:chlorine[level=7]",
        "kubejs:chlorine[level=8]",
        "kubejs:chlorine[level=9]",
        "kubejs:chlorine[level=10]",
        "kubejs:chlorine[level=11]",
        "kubejs:chlorine[level=12]",
        "kubejs:chlorine[level=13]",
        "kubejs:chlorine[level=14]",
        "kubejs:chlorine[level=15]",
        "kubejs:caustic_soda[level=1]",
        "kubejs:caustic_soda[level=2]",
        "kubejs:caustic_soda[level=3]",
        "kubejs:caustic_soda[level=4]",
        "kubejs:caustic_soda[level=5]",
        "kubejs:caustic_soda[level=6]",
        "kubejs:caustic_soda[level=7]",
        "kubejs:caustic_soda[level=8]",
        "kubejs:caustic_soda[level=9]",
        "kubejs:caustic_soda[level=10]",
        "kubejs:caustic_soda[level=11]",
        "kubejs:caustic_soda[level=12]",
        "kubejs:caustic_soda[level=13]",
        "kubejs:caustic_soda[level=14]",
        "kubejs:caustic_soda[level=15]",
        "kubejs:nitric_acid[level=1]",
        "kubejs:nitric_acid[level=2]",
        "kubejs:nitric_acid[level=3]",
        "kubejs:nitric_acid[level=4]",
        "kubejs:nitric_acid[level=5]",
        "kubejs:nitric_acid[level=6]",
        "kubejs:nitric_acid[level=7]",
        "kubejs:nitric_acid[level=8]",
        "kubejs:nitric_acid[level=9]",
        "kubejs:nitric_acid[level=10]",
        "kubejs:nitric_acid[level=11]",
        "kubejs:nitric_acid[level=12]",
        "kubejs:nitric_acid[level=13]",
        "kubejs:nitric_acid[level=14]",
        "kubejs:nitric_acid[level=15]",
        "kubejs:cryogen[level=1]",
        "kubejs:cryogen[level=2]",
        "kubejs:cryogen[level=3]",
        "kubejs:cryogen[level=4]",
        "kubejs:cryogen[level=5]",
        "kubejs:cryogen[level=6]",
        "kubejs:cryogen[level=7]",
        "kubejs:cryogen[level=8]",
        "kubejs:cryogen[level=9]",
        "kubejs:cryogen[level=10]",
        "kubejs:cryogen[level=11]",
        "kubejs:cryogen[level=12]",
        "kubejs:cryogen[level=13]",
        "kubejs:cryogen[level=14]",
        "kubejs:cryogen[level=15]",
        "kubejs:saline_water[level=1]",
        "kubejs:saline_water[level=2]",
        "kubejs:saline_water[level=3]",
        "kubejs:saline_water[level=4]",
        "kubejs:saline_water[level=5]",
        "kubejs:saline_water[level=6]",
        "kubejs:saline_water[level=7]",
        "kubejs:saline_water[level=8]",
        "kubejs:saline_water[level=9]",
        "kubejs:saline_water[level=10]",
        "kubejs:saline_water[level=11]",
        "kubejs:saline_water[level=12]",
        "kubejs:saline_water[level=13]",
        "kubejs:saline_water[level=14]",
        "kubejs:saline_water[level=15]",
        "create:honey[level=1]",
        "create:honey[level=2]",
        "create:honey[level=3]",
        "create:honey[level=4]",
        "create:honey[level=5]",
        "create:honey[level=6]",
        "create:honey[level=7]",
        "create:honey[level=8]",
        "create:honey[level=9]",
        "create:honey[level=10]",
        "create:honey[level=11]",
        "create:honey[level=12]",
        "create:honey[level=13]",
        "create:honey[level=14]",
        "create:honey[level=15]",
        "minecraft:water[level=1]",
        "minecraft:water[level=2]",
        "minecraft:water[level=3]",
        "minecraft:water[level=4]",
        "minecraft:water[level=5]",
        "minecraft:water[level=6]",
        "minecraft:water[level=7]",
        "minecraft:water[level=8]",
        "minecraft:water[level=9]",
        "minecraft:water[level=10]",
        "minecraft:water[level=11]",
        "minecraft:water[level=12]",
        "minecraft:water[level=13]",
        "minecraft:water[level=14]",
        "minecraft:water[level=15]",
        "minecraft:lava[level=1]",
        "minecraft:lava[level=2]",
        "minecraft:lava[level=3]",
        "minecraft:lava[level=4]",
        "minecraft:lava[level=5]",
        "minecraft:lava[level=6]",
        "minecraft:lava[level=7]",
        "minecraft:lava[level=8]",
        "minecraft:lava[level=9]",
        "minecraft:lava[level=10]",
        "minecraft:lava[level=11]",
        "minecraft:lava[level=12]",
        "minecraft:lava[level=13]",
        "minecraft:lava[level=14]",
        "minecraft:lava[level=15]"
    ]
    function EmptyingFluidOut(fluid) {
        event.custom({
            "type": "custommachinery:custom_machine",
            "machine": "dut:emptying_machine",
            "time": 1,
            "priority": 1,
            "hidden": false,
            "error": true,
            "requirements": [{
                "type": "custommachinery:fluid",
                "mode": "input",
                "fluid": fluid,
                "amount": 1000
            },
            {
                "type": "custommachinery:block",
                "mode": "input",
                "action": "replace_destroy",
                "amount": 1,
                "pos": [0, -1, 0, 0, -1, 0],
                "filter": EmptyingFluidFilter,
                "whitelist": true,
                "block": fluid
            }
            ]
        }).id("dut_create:emptying_machine/output_" + fluid.split(":")[1])
    }
    EmptyingFluidOut("kubejs:hydrogen")
    EmptyingFluidOut("kubejs:nitrogen_dioxide")
    EmptyingFluidOut("kubejs:chlorine")
    EmptyingFluidOut("kubejs:oxygen")
    EmptyingFluidOut("kubejs:caustic_soda")
    EmptyingFluidOut("kubejs:nitric_acid")
    EmptyingFluidOut("minecraft:lava")
    EmptyingFluidOut("create:honey")
    EmptyingFluidOut("kubejs:cryogen")
    EmptyingFluidOut("kubejs:saline_water")

})